repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-ast
    - id: check-yaml
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      args: [--line-length=120]
- repo: local
  hooks:
    - id: test
      name: run pytest
      language: system
      entry: pytest
      pass_filenames: false
      types: [python]